sudo: false
language: java
jdk:
  - openjdk11
  - openjdk8
cache:
  directories:
    - "$HOME/.m2/repository"
before_cache:
  - rm -rf $HOME/.m2/repository/org/joda/beans
# install
install:
  - mvn --version
script:
  - mvn install site -e -B
after_success:
  - if [[ $TRAVIS_TAG =~ ^website.*$ ]] && [ "$TRAVIS_JDK_VERSION" == "openjdk11" ]; then chmod +x ./.github/website.sh; .github/website.sh; fi
  - if [[ $TRAVIS_TAG =~ ^v.*$ ]] && [ "$TRAVIS_PULL_REQUEST" == "false" ] && [ "$TRAVIS_JDK_VERSION" == "openjdk11" ]; then chmod +x ./.github/website.sh; .github/website.sh; fi
# secure keys for GITHUB_TOKEN
env:
  global:
  - secure: YmDFOujoMUl3XM9TOuxOB5Osm1GZXncIOR8XrVGJoXKq92jEU3sYMqYYBmCnmlXsQE5ANUE4mwMfxSNdRfLROpGQ7uP8wT4aL9t0PX7iJt/yrpHfJGpSAg2jwkf6gDMJgQpXMTz4aSHH3PzXXbAY6Gm52ZsD5QiWL+i1aiRigsM=
