/*
 *  Copyright 2001-present Stephen Colebourne
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */
package org.joda.beans.sample;

import java.util.Map;
import java.util.NoSuchElementException;

import org.joda.beans.Bean;
import org.joda.beans.ImmutableBean;
import org.joda.beans.JodaBeanUtils;
import org.joda.beans.MetaBean;
import org.joda.beans.MetaProperty;
import org.joda.beans.gen.BeanDefinition;
import org.joda.beans.gen.PropertyDefinition;
import org.joda.beans.impl.direct.DirectFieldsBeanBuilder;
import org.joda.beans.impl.direct.DirectMetaBean;
import org.joda.beans.impl.direct.DirectMetaProperty;
import org.joda.beans.impl.direct.DirectMetaPropertyMap;

/**
 * Implements the Joda-Convert aware {@link Index} interface using a bean.
 */
@BeanDefinition(factoryName = "of")
//@FromStringFactory(factory = Index2.class)
public final class ImmIndex implements Index2, ImmutableBean {

    public static final Index2 ONE = new ImmIndex("One", 1);
    public static final Index2 TWO = new ImmIndex("Two", 2);

    @PropertyDefinition(validate = "notNull", overrideGet = true)
    private final String name;
    @PropertyDefinition(validate = "notNull", overrideGet = true)
    private final int number;

    //------------------------- AUTOGENERATED START -------------------------
    /**
     * The meta-bean for {@code ImmIndex}.
     * @return the meta-bean, not null
     */
    public static ImmIndex.Meta meta() {
        return ImmIndex.Meta.INSTANCE;
    }

    static {
        MetaBean.register(ImmIndex.Meta.INSTANCE);
    }

    /**
     * Obtains an instance.
     * @param name  the value of the property, not null
     * @param number  the value of the property, not null
     * @return the instance
     */
    public static ImmIndex of(
            String name,
            int number) {
        return new ImmIndex(
            name,
            number);
    }

    /**
     * Returns a builder used to create an instance of the bean.
     * @return the builder, not null
     */
    public static ImmIndex.Builder builder() {
        return new ImmIndex.Builder();
    }

    private ImmIndex(
            String name,
            int number) {
        JodaBeanUtils.notNull(name, "name");
        JodaBeanUtils.notNull(number, "number");
        this.name = name;
        this.number = number;
    }

    @Override
    public ImmIndex.Meta metaBean() {
        return ImmIndex.Meta.INSTANCE;
    }

    //-----------------------------------------------------------------------
    /**
     * Gets the name.
     * @return the value of the property, not null
     */
    @Override
    public String getName() {
        return name;
    }

    //-----------------------------------------------------------------------
    /**
     * Gets the number.
     * @return the value of the property, not null
     */
    @Override
    public int getNumber() {
        return number;
    }

    //-----------------------------------------------------------------------
    /**
     * Returns a builder that allows this bean to be mutated.
     * @return the mutable builder, not null
     */
    public Builder toBuilder() {
        return new Builder(this);
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == this) {
            return true;
        }
        if (obj != null && obj.getClass() == this.getClass()) {
            ImmIndex other = (ImmIndex) obj;
            return JodaBeanUtils.equal(name, other.name) &&
                    (number == other.number);
        }
        return false;
    }

    @Override
    public int hashCode() {
        int hash = getClass().hashCode();
        hash = hash * 31 + JodaBeanUtils.hashCode(name);
        hash = hash * 31 + JodaBeanUtils.hashCode(number);
        return hash;
    }

    @Override
    public String toString() {
        StringBuilder buf = new StringBuilder(96);
        buf.append("ImmIndex{");
        buf.append("name").append('=').append(name).append(',').append(' ');
        buf.append("number").append('=').append(JodaBeanUtils.toString(number));
        buf.append('}');
        return buf.toString();
    }

    //-----------------------------------------------------------------------
    /**
     * The meta-bean for {@code ImmIndex}.
     */
    public static final class Meta extends DirectMetaBean {
        /**
         * The singleton instance of the meta-bean.
         */
        static final Meta INSTANCE = new Meta();

        /**
         * The meta-property for the {@code name} property.
         */
        private final MetaProperty<String> name = DirectMetaProperty.ofImmutable(
                this, "name", ImmIndex.class, String.class);
        /**
         * The meta-property for the {@code number} property.
         */
        private final MetaProperty<Integer> number = DirectMetaProperty.ofImmutable(
                this, "number", ImmIndex.class, Integer.TYPE);
        /**
         * The meta-properties.
         */
        private final Map<String, MetaProperty<?>> metaPropertyMap$ = new DirectMetaPropertyMap(
                this, null,
                "name",
                "number");

        /**
         * Restricted constructor.
         */
        private Meta() {
        }

        @Override
        protected MetaProperty<?> metaPropertyGet(String propertyName) {
            switch (propertyName.hashCode()) {
                case 3373707:  // name
                    return name;
                case -1034364087:  // number
                    return number;
            }
            return super.metaPropertyGet(propertyName);
        }

        @Override
        public ImmIndex.Builder builder() {
            return new ImmIndex.Builder();
        }

        @Override
        public Class<? extends ImmIndex> beanType() {
            return ImmIndex.class;
        }

        @Override
        public Map<String, MetaProperty<?>> metaPropertyMap() {
            return metaPropertyMap$;
        }

        //-----------------------------------------------------------------------
        /**
         * The meta-property for the {@code name} property.
         * @return the meta-property, not null
         */
        public MetaProperty<String> name() {
            return name;
        }

        /**
         * The meta-property for the {@code number} property.
         * @return the meta-property, not null
         */
        public MetaProperty<Integer> number() {
            return number;
        }

        //-----------------------------------------------------------------------
        @Override
        protected Object propertyGet(Bean bean, String propertyName, boolean quiet) {
            switch (propertyName.hashCode()) {
                case 3373707:  // name
                    return ((ImmIndex) bean).getName();
                case -1034364087:  // number
                    return ((ImmIndex) bean).getNumber();
            }
            return super.propertyGet(bean, propertyName, quiet);
        }

        @Override
        protected void propertySet(Bean bean, String propertyName, Object newValue, boolean quiet) {
            metaProperty(propertyName);
            if (quiet) {
                return;
            }
            throw new UnsupportedOperationException("Property cannot be written: " + propertyName);
        }

    }

    //-----------------------------------------------------------------------
    /**
     * The bean-builder for {@code ImmIndex}.
     */
    public static final class Builder extends DirectFieldsBeanBuilder<ImmIndex> {

        private String name;
        private int number;

        /**
         * Restricted constructor.
         */
        private Builder() {
        }

        /**
         * Restricted copy constructor.
         * @param beanToCopy  the bean to copy from, not null
         */
        private Builder(ImmIndex beanToCopy) {
            this.name = beanToCopy.getName();
            this.number = beanToCopy.getNumber();
        }

        //-----------------------------------------------------------------------
        @Override
        public Object get(String propertyName) {
            switch (propertyName.hashCode()) {
                case 3373707:  // name
                    return name;
                case -1034364087:  // number
                    return number;
                default:
                    throw new NoSuchElementException("Unknown property: " + propertyName);
            }
        }

        @Override
        public Builder set(String propertyName, Object newValue) {
            switch (propertyName.hashCode()) {
                case 3373707:  // name
                    this.name = (String) newValue;
                    break;
                case -1034364087:  // number
                    this.number = (Integer) newValue;
                    break;
                default:
                    throw new NoSuchElementException("Unknown property: " + propertyName);
            }
            return this;
        }

        @Override
        public Builder set(MetaProperty<?> property, Object value) {
            super.set(property, value);
            return this;
        }

        @Override
        public ImmIndex build() {
            return new ImmIndex(
                    name,
                    number);
        }

        //-----------------------------------------------------------------------
        /**
         * Sets the name.
         * @param name  the new value, not null
         * @return this, for chaining, not null
         */
        public Builder name(String name) {
            JodaBeanUtils.notNull(name, "name");
            this.name = name;
            return this;
        }

        /**
         * Sets the number.
         * @param number  the new value, not null
         * @return this, for chaining, not null
         */
        public Builder number(int number) {
            JodaBeanUtils.notNull(number, "number");
            this.number = number;
            return this;
        }

        //-----------------------------------------------------------------------
        @Override
        public String toString() {
            StringBuilder buf = new StringBuilder(96);
            buf.append("ImmIndex.Builder{");
            buf.append("name").append('=').append(JodaBeanUtils.toString(name)).append(',').append(' ');
            buf.append("number").append('=').append(JodaBeanUtils.toString(number));
            buf.append('}');
            return buf.toString();
        }

    }

    //-------------------------- AUTOGENERATED END --------------------------
}
