/*
 *  Copyright 2001-present Stephen Colebourne
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */
package org.joda.beans.sample;

import java.io.Serializable;
import java.util.Map;
import java.util.NoSuchElementException;

import org.joda.beans.ImmutableBean;
import org.joda.beans.JodaBeanUtils;
import org.joda.beans.MetaBean;
import org.joda.beans.MetaProperty;
import org.joda.beans.TypedMetaBean;
import org.joda.beans.gen.BeanDefinition;
import org.joda.beans.gen.PropertyDefinition;
import org.joda.beans.impl.direct.DirectFieldsBeanBuilder;
import org.joda.beans.impl.direct.MinimalMetaBean;

import com.google.common.collect.ImmutableMap;

/**
 * Mock JavaBean, used for testing.
 */
@BeanDefinition(style = "minimal", factoryName = "of")
public final class ImmMappedIndex implements ImmutableBean, Serializable {

    /**
     * The map of data, keyed by an index.
     */
    @PropertyDefinition(validate = "notNull")
    private final ImmutableMap<Index, String> data;

    //------------------------- AUTOGENERATED START -------------------------
    /**
     * The meta-bean for {@code ImmMappedIndex}.
     */
    private static final TypedMetaBean<ImmMappedIndex> META_BEAN =
            MinimalMetaBean.of(
                    ImmMappedIndex.class,
                    new String[] {
                            "data"},
                    () -> new ImmMappedIndex.Builder(),
                    b -> b.getData());

    /**
     * The meta-bean for {@code ImmMappedIndex}.
     * @return the meta-bean, not null
     */
    public static TypedMetaBean<ImmMappedIndex> meta() {
        return META_BEAN;
    }

    static {
        MetaBean.register(META_BEAN);
    }

    /**
     * The serialization version id.
     */
    private static final long serialVersionUID = 1L;

    /**
     * Obtains an instance.
     * @param data  the value of the property, not null
     * @return the instance
     */
    public static ImmMappedIndex of(
            Map<Index, String> data) {
        return new ImmMappedIndex(
            data);
    }

    /**
     * Returns a builder used to create an instance of the bean.
     * @return the builder, not null
     */
    public static ImmMappedIndex.Builder builder() {
        return new ImmMappedIndex.Builder();
    }

    private ImmMappedIndex(
            Map<Index, String> data) {
        JodaBeanUtils.notNull(data, "data");
        this.data = ImmutableMap.copyOf(data);
    }

    @Override
    public TypedMetaBean<ImmMappedIndex> metaBean() {
        return META_BEAN;
    }

    //-----------------------------------------------------------------------
    /**
     * Gets the map of data, keyed by an index.
     * @return the value of the property, not null
     */
    public ImmutableMap<Index, String> getData() {
        return data;
    }

    //-----------------------------------------------------------------------
    /**
     * Returns a builder that allows this bean to be mutated.
     * @return the mutable builder, not null
     */
    public Builder toBuilder() {
        return new Builder(this);
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == this) {
            return true;
        }
        if (obj != null && obj.getClass() == this.getClass()) {
            ImmMappedIndex other = (ImmMappedIndex) obj;
            return JodaBeanUtils.equal(data, other.data);
        }
        return false;
    }

    @Override
    public int hashCode() {
        int hash = getClass().hashCode();
        hash = hash * 31 + JodaBeanUtils.hashCode(data);
        return hash;
    }

    @Override
    public String toString() {
        StringBuilder buf = new StringBuilder(64);
        buf.append("ImmMappedIndex{");
        buf.append("data").append('=').append(JodaBeanUtils.toString(data));
        buf.append('}');
        return buf.toString();
    }

    //-----------------------------------------------------------------------
    /**
     * The bean-builder for {@code ImmMappedIndex}.
     */
    public static final class Builder extends DirectFieldsBeanBuilder<ImmMappedIndex> {

        private Map<Index, String> data = ImmutableMap.of();

        /**
         * Restricted constructor.
         */
        private Builder() {
        }

        /**
         * Restricted copy constructor.
         * @param beanToCopy  the bean to copy from, not null
         */
        private Builder(ImmMappedIndex beanToCopy) {
            this.data = beanToCopy.getData();
        }

        //-----------------------------------------------------------------------
        @Override
        public Object get(String propertyName) {
            switch (propertyName.hashCode()) {
                case 3076010:  // data
                    return data;
                default:
                    throw new NoSuchElementException("Unknown property: " + propertyName);
            }
        }

        @SuppressWarnings("unchecked")
        @Override
        public Builder set(String propertyName, Object newValue) {
            switch (propertyName.hashCode()) {
                case 3076010:  // data
                    this.data = (Map<Index, String>) newValue;
                    break;
                default:
                    throw new NoSuchElementException("Unknown property: " + propertyName);
            }
            return this;
        }

        @Override
        public Builder set(MetaProperty<?> property, Object value) {
            super.set(property, value);
            return this;
        }

        @Override
        public ImmMappedIndex build() {
            return new ImmMappedIndex(
                    data);
        }

        //-----------------------------------------------------------------------
        /**
         * Sets the map of data, keyed by an index.
         * @param data  the new value, not null
         * @return this, for chaining, not null
         */
        public Builder data(Map<Index, String> data) {
            JodaBeanUtils.notNull(data, "data");
            this.data = data;
            return this;
        }

        //-----------------------------------------------------------------------
        @Override
        public String toString() {
            StringBuilder buf = new StringBuilder(64);
            buf.append("ImmMappedIndex.Builder{");
            buf.append("data").append('=').append(JodaBeanUtils.toString(data));
            buf.append('}');
            return buf.toString();
        }

    }

    //-------------------------- AUTOGENERATED END --------------------------
}
