name: Build

on: 
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - 'main'
  schedule:
    - cron: '41 19 * * 2'

permissions:
  contents: read

jobs:
  build:
    permissions:
      security-events: write  # for github/codeql-action
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: 21
        distribution: 'temurin'
        cache: 'maven'

    - name: Maven version
      run: |
        mkdir -p ./.mvn
        echo "-e" >> ./.mvn/maven.config
        echo "-B" >> ./.mvn/maven.config
        echo "-ntp" >> ./.mvn/maven.config
        echo "-DtrimStackTrace=false" >> ./.mvn/maven.config
        echo "--settings" >> ./.mvn/maven.config
        echo "$( pwd )/.github/maven-settings.xml" >> ./.mvn/maven.config
        mvn --version
        mkdir -p target

    #------------------------------------------------------------------------
    - name: Initialize CodeQL
      uses: github/codeql-action/init@v3
      with:
        languages: java

    - name: Maven build
      run: |
        mvn install site -Doss.build

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v3
