name: Build

on: 
  push:
    branches:
      - '*'
    tags:
      - 'v*'
      - 'website*'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [1.8, 11]
    
    steps:
    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.java }}
    - name: Checkout
      uses: actions/checkout@v2
    - name: Maven cache
      uses: actions/cache@v1
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ matrix.java }}-${{ hashFiles('**/pom.xml') }}-${{ hashFiles('.github/workflows/build.yml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    - name: Maven version
      run: |
        mkdir -p ./.mvn
        echo '-e -B -DtrimStackTrace=false' > ./.mvn/maven.config
        mvn --version
        mkdir -p target
    - name: Maven build
      run: |
        mvn install site

    - name: Website
      if: matrix.java == '11' && env.GITHUB_HEAD_REF == null
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_PERSONAL_TOKEN }}
      run: |
        if [[ $GITHUB_REF =~ ^refs[/]tags[/]website.*$ ]]; then chmod +x ./.github/website.sh; .github/website.sh; fi
        if [[ $GITHUB_REF =~ ^refs[/]tags[/]v.*$ ]]; then chmod +x ./.github/website.sh; .github/website.sh; fi
